export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const EMPTY_CONTACT ="EMPTY_CONTACT";
export const EDIT_OBJECT ="EDIT_OBJECT";
export const ADD_ADDRESS="ADD_ADDRESS"
export const ADDSTATMENT="ADD_STATMENT"
export const DELETESTATMENT="DELETESTATMENT"
export const DASHBOARD="DASHBOARD"